### PR TITLE
Made changes to the beginning of run_basketball

### PR DESCRIPTION
**Pull request by codefeld**
Also changed spaces to tabs.

### CODE REVIEW

**Comment by jkutner** [comment]
@Blastoff88 thanks for trying to merge, but the code isn't valid now

**Comment by jkutner** [comment]
@codefeld you'll need to run `git reset --hard edd6457` to undo the merge commit. then you can run `git merge master`, and you'll need to resolve the conflicts manually.

**Comment by codefeld** [comment]
@Blastoff88 I fixed the conflicts. Can you rereview?

**Review by HipsterDave — APPROVED** [review]

**Comment by codefeld** [comment]
This conflicts with master again, and some how the part where we back into the wall at the start was lost in the merge.

**Pull request closed without merging**
